# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peroid', models.IntegerField(default=-1)),
                ('data_limit', models.IntegerField(default=-1)),
                ('peroid_times', models.IntegerField(default=0)),
            ],
        ),
    ]
